### ISSUE TITLE
HTTP Request

### ISSUE THREAD

**Issue by DimiDerevo** [MeSoftHorny/WTRTI#27]
Hello, I`m trying to get "map_obj.json" with GetAsync but it takes 2-3 seconds. May I know the way you achieved such a fast requests?

**Comment by MeSoftHorny** [comment]
Hello.  C#? I guess you do not close the connection right after receiving the data, so the game does it by itself (timeout).
Can you show how you making request?

**Comment by DimiDerevo** [comment]
Yes, C#. I thought I shouldn't close connection to not waste time for establishing new connection. I'm new to network programming so sorry if it is a dumb question.

```
using (var client = new HttpClient())
{
    client.BaseAddress = new Uri("http://localhost:8111");

    HttpResponseMessage responseMapObj = client.GetAsync("/map_obj.json").Result;
    responseMapObj.EnsureSuccessStatusCode();
    string resultMapObj = responseMapObj.Content.ReadAsStringAsync().Result;
    Console.WriteLine("Result MapObj: \n" + resultMapObj);

}
```

**Comment by MeSoftHorny** [comment]
Yes, you're right, for better performance it's good not to close connections, but the problem is that the game doesn't like keep-alive connections, at least it did a few years ago when I tested it, not sure how it is now.
Unfortunately I'm not familiar with C#, but looking at your code, everything seems to be fine.
I can only recommend setting a timeout (100ms or something) for the connection.
